// User reducer types

export const UPDATE_COMPUTER_CHIPS = "UPDATE_COMPUTER_CHIPS";
export const UPDATE_HUMAN_CHIPS = "UPDATE_HUMAN_CHIPS";
export const SET_HANDS = "SET_HANDS";
export const SET_REMAINING_DECK = "SET_REMAINING_DECK";
