// User reducer types

export const UPDATE_COMPUTER_CHIPS = "UPDATE_COMPUTER_CHIPS";
export const UPDATE_HUMAN_CHIPS = "UPDATE_HUMAN_CHIPS";
export const SET_HANDS = "SET_HANDS";
export const SET_REMAINING_DECK = "SET_REMAINING_DECK";
export const SET_FLOP = "SET_FLOP";
export const SET_TURN = "SET_TURN";
export const SET_RIVER = "SET_RIVER";
export const UPDATE_POT = "UPDATE_POT";
export const UPDATE_GAMEPLAY = "UPDATE_GAMEPLAY";
export const SET_SMALLBLIND = "SET_SMALLBLIND";
export const CHANGE_GAMESTATE = "CHANGE_GAMESTATE";
export const SET_STRAIGHT_FLUSH = "SET_STRAIGHT_FLUSH";
export const EMPTY_POT = "EMPTY_POT";
export const SET_SHOWDOWN_DESCRIPTION = "SET_SHOWDOWN_DESCRIPTION";
